### ISSUE TITLE
Can we log detections to /tmp/Pisaver.log?

### ISSUE THREAD

**Issue by PineNappler** [WiPi-Hunter/PiSavar#3]
would be great to refer back to after running all day as you might not see it at the time of attack.

**Comment by besimaltnok** [comment]
can you give me some more information?

**Comment by PineNappler** [comment]
sure, if your watching the terminal when PineAP is detected then you will know there was a detection. 
If for example you left it running over night or over lunch break there currently is no way to know there was a detection. It would be great if the PiSavar phase could include some form of notification to let you know there was a detection in the past while you were AFK and to check the logs for details.

Useful info to log would be

Time stamp of first detection
MAC address of the PineAP
List of SSID's used in the attack
Time stamp PineAP was no longer detected
+ anything else that might be useful 

I ran this on my Wifi Pineapple Tetra and it worked very well as a static situation, I am currently trying to get scapy installed on the Wifi pineapple Nano to allow it to be to be a mobile pineapple hunter/detector. Its a useful tool, thank you.

**Comment by besimaltnok** [comment]
New update for logging:

tail -f /var/log/pisavar.log
