### ISSUE TITLE
option to select radio to use for deauth

### ISSUE THREAD

**Issue by PineNappler** [WiPi-Hunter/PiSavar#5]
I run this on a wifi Pineapple and wlan0 is used for the management wifi connection to the pineapple. I edit the current wlan0mon radio to wlan1mon or wlan2mon when i need to. 
But it would be useful to be able to start the script and select the deauth radio at launch time as well as the sniffing interface.

**Comment by besimaltnok** [comment]
Thanks for the suggestions. I will publish an update. (BH Eu 2017 Arsenal)

**Comment by besimaltnok** [comment]
New update for select clan interface:

with -i
